name: Go Reviewdog

on:
  pull_request:
    types: [opened, synchronize]
    paths: '**.go'

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ github.token }}
          level: warning
          reporter: github-pr-review
