name: reviewdog
on: [pull_request]
jobs:
  ansible-lint:
    name: runner / ansible-lint 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          ansiblelint_version: 5.3.2
