name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.6

      - name: ansible-lint github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          ansiblelint_flags: "testdata/test.yml"

      - name: ansible-lint github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          ansiblelint_flags: "testdata/test.yml"

      - name: ansible-lint github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          ansiblelint_flags: "testdata/test.yml"
